spring:
  profiles:
    active: local
  application:
    name: ai-code-generater-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_generater
    username: root
    password: 123456
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.goblin.aicodergenerater.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.moonshot.cn/v1 # https://api.deepseek.com
      api-key: xxxx
      model-name: kimi-k2-turbo-preview # deepseek-chat
      log-requests: true
      log-responses: true
      max-retries: 0
      timeout: 120000
      max-tokens: 8192