spring:
  application:
    name: ai-code-screenshot
  profiles:
    active: local
server:
  port: 8127
  servlet:
    context-path: /api
# 添加 COS 对象存储配置 (使用s3)

s3:
  client:
    host: your-custom-domain.com
    accessKey: your-access-key
    secretKey: our-secret-key
    bucket: your-bucket-name
# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
